services:
  # === Backend ===
  - type: web
    name: hr-system-backend
    env: node
    rootDir: backend
    buildCommand: |
      npm install --include=dev
      npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://hr-system-fe.onrender.com
      - key: PORT
        value: 8000

  # === Frontend ===
  - type: web
    name: hr-system-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://hr-system-backend.onrender.com
