services:
  # === Backend API ===
  - type: web
    name: hr-system-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        value: https://hr-system-fe.onrender.com

  # === Frontend ===
  - type: static
    name: hr-system-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://hr-system-backend.onrender.com
